
///
export const FETCH_FOOD_LIST ='FETCH_FOOD_LIST';
export const FETCH_FOOD_LIST_SUCCESS ='FETCH _FOOD_LIST_SUCCESS';
export const FETCH_FOOD_LIST_FAILURE ='FETCH _FOOD_LIST_FAILURE';

export const SELECTED_MEAL_DETAILS ='SELECTED_MEAL_DETAILS'

export const FETCH_SELECTED_MEAL_INGREDIENTS='FETCH_SELECTED_MEAL_INGREDIENTS'
export const FETCH_SELECTED_MEAL_INGREDIENTS_SUCCESS='FETCH_SELECTED_MEAL_INGREDIENTS_SUCCESS'
export const FETCH_SELECTED_MEAL_INGREDIENTS_FAILURE='FETCH_SELECTED_MEAL_INGREDIENTS_FAILURE'


export const SHIPPING_INFORMATION_DETAILS ='SHIPPING_INFORMATION_DETAILS'

export const FETCH_SEARCH_MEALS='FETCH_SEARCH_MEALS'
export const FETCH_SEARCH_MEALS_SUCCESS='FETCH_SEARCH_MEALS_SUCCESS'
export const FETCH_SEARCH_MEALS_FAILURE='FETCH_SEARCH_MEALS_FAILURE'
